### PR TITLE
Holy Shit the fixes

### PR DESCRIPTION
**Pull request by HoaxIT**
new shit.

### CODE REVIEW

**Comment by Nienhaus** [comment]
Why not add it as a second type of Ripley that cost a tiny bit more but is a little faster?

**Comment by HoaxIT** [comment]
@Nienhaus sounds even better.

**Comment by Memendia** [comment]
@HoaxIT oh gawd duh code taking has begun

**Comment by danhibiki** [comment]
Really nex? You are the posterboy for making pulls from TG and you are calling someone out for making pulls?

**Comment by SplergeBucket** [comment]
shit nex figured out the plan
we're gunna steal all your code and afterwards i'll finish up by shitting or pissing (whichever comes out first) on the national flag of atlastokzka while reciting the australian national anthem
:^)
(^:
:+1:

**Pull request closed without merging**
