### PR TITLE
Adds in credit to the changelog

### PR DESCRIPTION
**Pull request by JamieH**

### CODE REVIEW

**Comment by Nokington** [comment]
Good luck with that.

**Comment by JamieH** [comment]
So you guys won't give us credit for stuff we did?

**Comment by danhibiki** [comment]
LOL

**Comment by Nokington** [comment]
How about you give credit to goon station Jamie? http://puu.sh/hsVuu/2d08dc54ce.png

**Comment by Crystalwarrior** [comment]
https://www.gnu.org/licenses/gpl-faq.en.html#IWantCredit

**Comment by JamieH** [comment]
Credit is given to Goon in the changelog already at the bottom, also at the time we were pretty open about it being the goon master controller. There is also credit in the entire folder the process scheduler sits in.

If you guys don't feel like that's enough credit - feel free to give it more credit, but don't just steal commits and not credit because you don't think I gave enough credit for the Goon MC.

**Comment by danhibiki** [comment]
I'd agree to the commit on line 1507 but the other ones are simple ridiculous. You've done enough advertising on our server.

**Comment by JamieH** [comment]
This isn't about advertising. Trust me, if we wanted to advertise we would. - This is about @HoaxIT slapping his name on our work and claiming it as his own.

**Comment by Nokington** [comment]
I agree with Dan. You want credit, it can be at the bottom of the changelog.

**Comment by danhibiki** [comment]
If a credit to goon for their MC at the bottom is enough for you (lol) then one at the bottom for Atlas should suffice

**Comment by HoaxIT** [comment]
@JamieH You did the same with the GoonStation scheduler, and many other upstream patches.

**Comment by JamieH** [comment]
@danhibiki - Sure, Lemme fix my patch to look like that. Hang on.

**Comment by JamieH** [comment]
@danhibiki there you go.

**Comment by danhibiki** [comment]
We are currently reviewing this commit.

**Comment by Iamgoofball** [comment]
Yeah, goonstation thank you has been in since tg. Should already be in there

**Pull request merged**
