### PR TITLE
Fixes issue #109, updates Changelog to reflect previous changes, adds completed Cargo to MockupStation

### PR DESCRIPTION
**Pull request by WitheredGryphon**
Ignore the previous PR to the main branch.

### CODE REVIEW

**Comment by WitheredGryphon** [comment]
The merge conflict is on html/changelog.html. Just needs to be updated since Derp pushed ahead of my PR

**Comment by Kokojos** [comment]
Yo Withered, any way I can get in contact with you? Your skype is dead.

**Comment by WitheredGryphon** [comment]
Yeah and my Skype's dead because I bought and built an entirely new computer (which is also why I haven't been mapping anything in the like past few months) so I had to set everything back up.

Shoot me an e-mail <myusername>@gmail.com and I'll get back with you.

**Comment by WitheredGryphon** [comment]
Closing this, no longer relevant.

**Pull request closed without merging**
